In [4]:
import time 
import warnings
import logging
import tensorflow as tf 

In [7]:
@tf.function
def add(a, b):
    return a + b

@tf.function
def sub(a, b): 
    return a - b

@tf.function
def mul(a, b):
    return a * b


In [4]:
print(add(tf.constant(6), tf.constant(7)))

tf.Tensor(13, shape=(), dtype=int32)


In [5]:
print(sub(tf.constant(6), tf.constant(7)))

tf.Tensor(-1, shape=(), dtype=int32)


In [31]:
@tf.function 
def matmul(a, b):
    return tf.matmul(a , b)


In [32]:
@tf.function
def linear(m, x, c):
    return add(matmul(m, x), c)

In [33]:
m = tf.constant([[4.0, 5.0, 6.0]], tf.float32)

m

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[4., 5., 6.]], dtype=float32)>

In [34]:
x = tf.Variable([[100.0], [100.0], [100.0]], tf.float32)

x

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[100.],
       [100.],
       [100.]], dtype=float32)>

In [21]:
c = tf.constant([[1.0]], tf.float32)

c

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

In [35]:
linear(m, x, c)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1501.]], dtype=float32)>

In [5]:
@tf.function
def pos_neg_cheack(x):
        reduce_sum = tf.reduce_sum(x)
        if reduce_sum > 0:
            return tf.constant(1)
        if reduce_sum == 0:
            return tf.constant(0)

        else:
            return tf.constant(-1)

        


In [6]:
pos_neg_cheack(tf.constant([100, 100]))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
num = tf.Variable(7)

In [9]:
@tf.function
def add_times(x):
    for i in tf.range(x):
        num.assign_add(x)

In [10]:
add_times(5)

In [11]:
print(num)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>


In [15]:
@tf.function
def square(a):
    print("input a:", a)
    return a*a 

In [16]:
x = tf.Variable([[2,2], [2,2]], dtype=tf.float32)

square(x)

input a: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32>


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [19]:
y = tf.Variable([[2,2], [2,2]], dtype=tf.int32)

square(y)

input a: <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 4],
       [4, 4]])>

In [20]:
z = tf.Variable([[1, 1], [1, 1]], dtype= tf.float32)

square(z)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [23]:
concrete_val_int = square.get_concrete_function(tf.TensorSpec(shape=None, dtype=tf.int32))

concrete_val_int

input a: Tensor("a:0", dtype=int32)


<ConcreteFunction square(a) at 0x1B7044EBEB0>

In [24]:
concrete_val_float = square.get_concrete_function(tf.TensorSpec(shape=None, dtype=tf.float32))

concrete_val_float

input a: Tensor("a:0", dtype=float32)


<ConcreteFunction square(a) at 0x1B7044F41F0>

In [25]:
concrete_val_float(tf.constant([[2,2], [2,2]], dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [27]:
concrete_val_int(tf.constant([[2,2], [2,2]], dtype=tf.int32))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 4],
       [4, 4]])>

In [28]:
@tf.function
def f(x):
    print('execution of ', x)
    tf.print('graph execution', x)

In [29]:
f(1)

execution of  1
graph execution 1


In [30]:
f(1)

graph execution 1


In [31]:
@tf.function 
def fn_with_varable():
    a = tf.constant([[10,10],[11., 1.]])
    x = tf.constant([[1., 0.],[0., 1.]])
    b = tf.Variable(12.)
    
    y = tf.matmul(a, x) + b
    
    tf.print("tf_print", y)
    return y

In [32]:
fn_with_varable()

ValueError: in user code:

    File "C:\Users\MICHEA~1\AppData\Local\Temp/ipykernel_12820/358970845.py", line 5, in fn_with_varable  *
        b = tf.Variable(12.)

    ValueError: tf.function only supports singleton tf.Variables created on the first call. Make sure the tf.Variable is only created once or created outside tf.function. See https://www.tensorflow.org/guide/function#creating_tfvariables for more information.


In [34]:
class F():
    def __init__(self):
        self._b = None
    
    @tf.function
    def __call__(self):
        a = tf.constant([[10,10],[11., 1.]])
        x = tf.constant([[1., 0.],[0., 1.]])
        
        if self._b is None:
            self._b = tf.Variable(12.)
            
        y = tf.matmul(a, x) + self._b
        print(y)
        
        tf.print('tf_print:', y)
        return y
        
fn_with_varable = F()


fn_with_varable()

Tensor("add:0", shape=(2, 2), dtype=float32)
Tensor("add:0", shape=(2, 2), dtype=float32)
tf_print: [[22 22]
 [23 13]]


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 22.],
       [23., 13.]], dtype=float32)>

In [35]:
def f(x):
    if x > 0:
        x*= x
    return x
    
print(tf.autograph.to_code(f)) 

def tf__f(x):
    with ag__.FunctionScope('f', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()

        def get_state():
            return (x,)

        def set_state(vars_):
            nonlocal x
            (x,) = vars_

        def if_body():
            nonlocal x
            x = ag__.ld(x)
            x *= x

        def else_body():
            nonlocal x
            pass
        ag__.if_stmt(ag__.ld(x) > 0, if_body, else_body, get_state, set_state, ('x',), 1)
        try:
            do_return = True
            retval_ = ag__.ld(x)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)

